<a href="https://colab.research.google.com/github/UpendraVishwanathYS/Toeplitz-Matrix-for-Convolution/blob/main/Computation_of_Convolution_using_Toeplitz_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1-D convolution using Toeplitz matrix
import numpy as np
from scipy import linalg as LA
x = np.array([1,2,3])
h = np.array([1,1])
zeros = np.zeros((1,len(x)-1))
p = np.block([h[1],zeros])
h = np.block([h,zeros])

t = LA.toeplitz(h,p)
y = t.dot(x)
print(y)


[1. 3. 5. 3.]


In [ ]:
# 2D convolution using toeplitz matrix
x = np.matrix([[1,2],[3,4]])
h = np.matrix([[5,6],[7,8]])
rx,cx = x.shape
rh,ch = h.shape


def toeplitz_blocks(x,h):
  rx,cx = x.shape
  rh,ch = h.shape
  zeros = np.zeros((1,ch))
  p = np.block([x,np.zeros((1,ch-1))])
  t = LA.toeplitz(p,zeros)
  return t

for j in range(0,x.shape[0]):
  u = x[j]
  t = toeplitz_blocks(u,h)
  if j==0:
    inputs = (t,)
    b = np.block([t])
  else: 
    b = np.block([b,t])
    t = (t,)
    inputs += t

# b = [H0,H1,H2]

nh = len(inputs)
nrows = 2*nh - 1
m, n = inputs[0].shape

T = np.zeros((nrows, m, nh, n), dtype=H1.dtype)
for i, H in enumerate(inputs):
    for j in range(nh):
        T[i + j, :, j, :] = H

T.shape = (nrows*m, nh*n)


h.shape = (h.size,1)
y = T.dot(h)
y.shape = (rx+rh-1,cx+ch-1)
print(y)




[[ 5 16 12]
 [22 60 40]
 [21 52 32]]
